### ISSUE TITLE
Install essential software packages

### ISSUE THREAD

**Issue by AndreWeiner** [nformella/Cluster-based-network-modeling-using-auto-encoders#1]
Hi Niels,
the first software packages you'll need are:
- Numpy for array-operations
- Matplotlib for plotting
- pyTorch for deep learning
- Jupyterlab for creating interactive documents

An easy way to install Python packages is *pip*. Under Ubuntu, you can install *pip* using apt:
```
sudo apt install pip3
```
Additionally, you'll need Latex and Pandoc to render nicer plots and to export Jupyter notebooks to HTML or PDF:

```
sudo apt install texlive-xetex texlive-fonts-recommended texlive-generic-recommended pandoc
```
Now you can install Python packages via:
```
pip3 install numpy matplotlib jupyterlab torch torchvision
```
Let me know if this works for you.
Best, Andre

**Comment by nformella** [comment]
Hi Andre,

right now I only have Windows installed on my laptop. Do you recommend to also have an Ubuntu system on it? I am running quite low on memory on my SSD on which Windows is installed.

I just took a closer look at gitHub. Will see if you get notified about this message ;).

Best, Niels

**Comment by AndreWeiner** [comment]
Hi Niels,

using Ubuntu via [Linux subsystem for Windows](https://ubuntu.com/tutorials/ubuntu-on-windows#1-overview) is fine for this project. I personally prefer to have a pure Linux installation, but I do not rely on Windows. Installing Windows and Ubuntu side-by-side is also straight forward, [click](https://linuxconfig.org/how-to-install-ubuntu-20-04-alongside-windows-10-dual-boot).

Large simulation data will be processed on the cluster, but you should have at least 20-50 GB on your local system for convenient experimentation with the data. Hope this answers your question.

Best, Andre
