### ISSUE TITLE
Perform 2D simulation of the flow past a cylinder at Re=100

### ISSUE THREAD

**Issue by AndreWeiner** [nformella/Cluster-based-network-modeling-using-auto-encoders#4]
This issue depends on issue #3. The base case is available in the [flowTorch](https://github.com/AndreWeiner/flowtorch/tree/main/test/test_data/test_cases/of_cylinder2D_binary) repository. Add this folder to your repository, e.g., under *test_cases/2D_cylinder_flow/*, and have a look at the files and folders comprising the simulation setup. One possible workflow to run the simulation with the Singularity container is
```
# I assume you're in the top-level folder of your repository
# the following steps only have to be executed once
# create a *.gitignore* file if it doesn't already exist
touch .gitignore
# open the ignore file and add a line with *run* or use
echo "run" >> .gitignore
# create a run-folder (we don't want this folder to be tracked by Git)
mkdir run

# the following steps are performed whenever you run new simulations
# copy the simulation folder to the run folder
cp -r test_cases/2D_cylinder_flow run/
# start a shell in the container
singularity shell name_of_openfoam_image
# now you are inside the container
# navigate to the cylinder simulation case
cd run/2D_cylinder_flow
# source OpenFOAM environment variables; you may have to change this to openfoam2012 if you use a newer version
. /usr/lib/openfoam/openfoam2006/etc/bashrc
# execute the Allrun script
./Allrun
```
For a visual inspection, install ParaView using `sudo apt install paraview`, go to the simulation case, and run
```
touch post.foam # usually this file is already present
paraview post.foam
```

Let me know if this works for you.
Best, Andre

**Comment by nformella** [comment]
Simulation runs fine and I am able to see the results in paraview.
