### ISSUE TITLE
Getting started with OpenFOAM

### ISSUE THREAD

**Issue by AndreWeiner** [nformella/Cluster-based-network-modeling-using-auto-encoders#5]
Hi Niels,

Have a look at the the [lid-driven cavity tutorial](https://openfoam.com/documentation/tutorial-guide/tutorialse2.php#x6-60002.1) in the OpenFOAM tutorial collection. To get started, copy the tutorial case into your run directory and follow the instructions provided in the documentation. In addition to the default means of post-processing, try to activate ParaView's [LIC](https://www.paraview.org/Wiki/ParaView/Line_Integral_Convolution) representation (line integral convolution) and post a visualization of the flow field in this issue once you're done.

Best, Andre

**Comment by nformella** [comment]
![cavity_surfaceLIC](https://user-images.githubusercontent.com/76008765/107748548-881acd80-6d19-11eb-8d76-74278f5e49b0.png)

**Comment by nformella** [comment]
I still have to figure out how to get better figures in paraview and adjust them the way I want. Plenty of tutorials online...
